development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:  root
  password: develop
  database: rails_quick-start_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:  root
  password: develop
  database: rails_quick-start_test
