development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  sql_mode: TRADITIONAL
  variables:
    sql_mode: TRADITIONAL
  host: localhost
  port: 3306
  username: root
  password: develop
  database: rails_quick-start_development

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  sql_mode: TRADITIONAL
  variables:
    sql_mode: TRADITIONAL
  host: localhost
  port: 3306
  username: root
  password: develop
  database: rails_quick-start_test
