overall:
  url: 'http://localhost:3000'
  timezone: 'Riga' # list timezones: ActiveSupport::TimeZone.all.map(&:name)

locales:
  default:   'en'
  visible:   ['en'] # locales publicly visible
  available: ['en'] # locales in project. Usually add here first, so admin can translate views in admin panel
  fallbacks:
    en: ['en']

mailer:
  default_from: 'no-reply@example.com'

redis:
  url: 'redis://localhost:6379/1'
  namespace: <%= "rails_quick_start_#{Rails.env}" %>

# Workers config here is ignored in development,
# if Procfile is used to run resque.
# It only affects rake resque workers.
resque:
  verbose: true
  wait_before_kill: 20 # seconds
  workers:
    -
      enabled:  true # change to false and run rake resque:restart_workers
      queues:   ['default']
      interval: 1 # seconds

resque_scheduler:
  verbose: true
  pid_path: '/tmp/pids/resque_scheduler.pid'
  interval: 1 # seconds
  jobs:
